In [1]:
# stdlib
import warnings
warnings.filterwarnings("ignore")
# third party
from sklearn.datasets import load_diabetes
# synthcity absolute
from synthcity.plugins import Plugins
eval_plugin = "syn_seq"
# synthcity absolute
from synthcity.plugins.core.dataloader import Syn_SeqDataLoader
X, y = load_diabetes(return_X_y=True, as_frame=True)
X["target"] = y

[KeOps] Warning : omp.h header is not in the path, disabling OpenMP. To fix this, you can set the environment
                  variable OMP_PATH to the location of the header before importing keopscore or pykeops,
                  e.g. using os.environ: import os; os.environ['OMP_PATH'] = '/path/to/omp/header'
[KeOps] Warning : Cuda libraries were not detected on the system or could not be loaded ; using cpu only mode

In [2]:
user_custom = {
  'syn_order' : ['sex', 'bmi', 'age', 'bp', 's1', 's2', 's3', 's4', 's5', 's6', 'target'],
  'method' : {'bp':'norm'},
  'col_type' : {"age": "category", "sex": "category"},
  'variable_selection' : {
    "s4": ['sex', 'bmi', 'age', 'bp', 's1', 's2'],
    "target": ['sex', 'bmi', 'age', 'bp', 's1', 's2', 's3'],
  }
}

In [3]:
loader = Syn_SeqDataLoader(X, target_column="target", sensitive_columns=["sex"], user_custom = user_custom)

[INFO] Syn_SeqEncoder summary:
  - syn_order: ['sex', 'bmi', 'age', 'bp', 's1', 's2', 's3', 's4', 's5', 's6', 'target']
  - original_dtype => {'sex': 'float64', 'bmi': 'float64', 'age': 'float64', 'bp': 'float64', 's1': 'float64', 's2': 'float64', 's3': 'float64', 's4': 'float64', 's5': 'float64', 's6': 'float64', 'target': 'float64'}
  - converted_type => {'sex': 'category', 'bmi': 'numeric', 'age': 'category', 'bp': 'numeric', 's1': 'numeric', 's2': 'numeric', 's3': 'numeric', 's4': 'numeric', 's5': 'numeric', 's6': 'numeric', 'target': 'numeric'}
  - method => {'sex': 'swr', 'bmi': 'cart', 'age': 'cart', 'bp': 'norm', 's1': 'cart', 's2': 'cart', 's3': 'cart', 's4': 'cart', 's5': 'cart', 's6': 'cart', 'target': 'cart'}
  - special_value => {}
  - date_mins => {}
  - variable_selection_:
        sex  bmi  age  bp  s1  s2  s3  s4  s5  s6  target
sex       0    0    0   0   0   0   0   0   0   0       0
bmi       1    0    0   0   0   0   0   0   0   0       0
age       1    1    0   0   0   0   0   0   0   0       0
bp        1    1    1   0   0   0   0   0   0   0       0
s1        1    1    1   1   0   0   0   0   0   0       0
s2        1    1    1   1   1   0   0   0   0   0       0
s3        1    1    1   1   1   1   0   0   0   0       0
s4        1    1    1   1   1   1   0   0   0   0       0
s5        1    1    1   1   1   1   1   1   0   0       0
s6        1    1    1   1   1   1   1   1   1   0       0
target    1    1    1   1   1   1   1   0   0   0       0
------------------------------------------------

In [4]:
Plugins().list()

[2025-01-21T01:03:28.560744+0900][7709][CRITICAL] module disabled: /Users/minkeychang/synthcity/src/synthcity/plugins/generic/plugin_goggle.py

['image_cgan',
 'survae',
 'pategan',
 'syn_seq',
 'ctgan',
 'arf',
 'timegan',
 'radialgan',
 'decaf',
 'rtvae',
 'adsgan',
 'uniform_sampler',
 'privbayes',
 'tvae',
 'ddpm',
 'bayesian_network',
 'marginal_distributions',
 'timevae',
 'survival_nflow',
 'aim',
 'survival_ctgan',
 'dummy_sampler',
 'image_adsgan',
 'survival_gan',
 'great',
 'nflow',
 'fflows',
 'dpgan']

In [5]:
syn_model = Plugins().get("syn_seq")

[2025-01-21T01:03:29.393719+0900][7709][CRITICAL] module disabled: /Users/minkeychang/synthcity/src/synthcity/plugins/generic/plugin_goggle.py

In [6]:
syn_model.fit(loader)

In [7]:
syn_model.generate(nrows = len(X)).dataframe()

,sex,bmi,age,bp,s1,s2,s3,s4,s5,s6,target
0,0.050680,-0.009439,0.052606,0.090734,-0.009825,-0.002253,-0.021311,0.071210,0.079122,0.135612,283.0
1,-0.044642,0.026128,0.016281,0.021633,-0.060735,-0.052983,-0.069172,-0.076395,-0.030748,0.003064,232.0
2,-0.044642,-0.065486,-0.041840,0.000507,-0.007073,-0.019476,0.041277,-0.039493,-0.003301,0.003064,153.0
3,0.050680,-0.001895,0.005383,0.101339,0.087868,0.107662,-0.039719,0.108111,0.039542,0.135612,292.0
4,0.050680,0.059541,-0.030942,0.097735,-0.126781,-0.106845,0.015505,-0.047981,-0.046883,-0.030072,52.0
...,...,...,...,...,...,...,...,...,...,...,...
437,-0.044642,0.092953,0.027178,0.030473,-0.034592,-0.014466,-0.032356,-0.002592,-0.019198,-0.009362,270.0
438,0.050680,-0.025607,0.063504,0.048375,-0.007073,-0.005072,-0.010266,-0.002592,0.026717,0.019633,185.0
439,-0.044642,0.104809,0.030811,0.038334,-0.011201,-0.013214,-0.058127,0.034309,0.060791,0.019633,270.0
440,0.050680,-0.033151,-0.001882,-0.019251,-0.009825,0.004949,-0.013948,-0.002592,-0.011897,-0.075636,71.0
441,-0.044642,-0.050396,0.063504,-0.056601,0.043837,-0.015719,0.063367,-0.076395,-0.011897,-0.046641,89.0

In [8]:
loader

,sex,bmi,age,bp,s1,s2,s3,s4,s5,s6,target
0,0.050680,0.061696,0.038076,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.044642,-0.051474,-0.001882,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.050680,0.044451,0.085299,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.044642,-0.011595,-0.089063,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,-0.044642,-0.036385,0.005383,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.050680,0.019662,0.041708,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,0.050680,-0.015906,-0.005515,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.050680,-0.015906,0.041708,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.044642,0.039062,-0.045472,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.044642,-0.073030,-0.045472,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [9]:
X

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0